# Generated by Django 3.1.7 on 2021-03-24 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_upload_document_created_by', related_query_name='bulk_upload_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_upload_document_updated_by', related_query_name='bulk_upload_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=15)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_upload.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_upload.schema')),
            ],
        ),
    ]
