name: Deploy workflow
on:
  push: 
    branches: [ main ]

jobs: 
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_DROPLET }}
          username: root
          password: ${{ secrets.DIGITAL_OCEAN_PASSWORD }}
          port: 22
          script: |
            cd backend
            git pull origin main
            git status
            docker-compose -f docker-compose.prod.yml build
            docker-compose -f docker-compose.prod.yml up -d
            docker-compose -f docker-compose.prod.yml exec web python manage.py migrate --noinput


